# Generated by Django 3.1.5 on 2021-01-29 05:03

from django.db import migrations, models
import django.db.models.deletion
import ecommerce.product.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID da categoria')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID do produto')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('value', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='valor')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='quantidade em estoque')),
                ('image', models.ImageField(blank=True, null=True, upload_to=ecommerce.product.models.product_image_directory_path, verbose_name='imagem')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['created'],
            },
        ),
    ]
